site_name: ACEL Wiki
#theme: readthedocs
theme_dir: cinder
site_author: acel
site_description: "ACEL wiki pages organized using mkdocs with cinder theme"
repo_url: "https://github.com/ace-lab-wpi/acel-wiki.git"
copyright: "This documentation is © Copyright 2017 ACEL."
#google_analytics: ['', '']
pages:
  - Home: index.md
  - General:
      - 'Workbench': 'general/workbench.md'
      - 'Robot Platforms': 'general/robots.md'
  - HOW-TOs:
      - 'How to solder': 'howtos/how-to-solder.md'
  - Contribute:
      - 'General Guide': 'contribute/general-guide.md'      
#  - Specimen: specimen.md
