site_name: Development Guide - dRonin
theme_dir: cinder
site_author: dRonin
site_description: "dRonin wiki pages organized using mkdocs with cinder theme"
repo_url: "https://github.com/rxdu/dRonin-docs"
copyright: "Cinder is licensed under the <a href='https://github.com/chrissimpkins/cinder/blob/master/LICENSE.md'>MIT license</a>"
pages:
  - Home: index.md
  - Specimen: specimen.md
